Online-Game-Store/GameShop/gameshop/urls.py
# coding=utf-8
from django.conf.urls import url, include
from django.contrib.sites.models import Site

#from . import admin
from . import views
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^register$', views.register, name='register'),
    url(r'^profile$', views.profile, name='profile'),
    url(r'^shop$', views.shop, name='shop'),
    url(r'^play/(?P<game_id>[0-9]+)/$', views.play, name='play'),
    url(r'^payment$', views.payment, name='payment'),
    url(r'^developer$', views.developer, name='developer'),
    url(r'^add$', views.add_game, name='add'),
    url(r'^modify/(?P<game_id>[0-9]+)/$', views.modify_game, name='modify'),
    url(r'^remove/(?P<game_id>[0-9]+)/$', views.remove_game, name='remove'),
    url(r'^search$', views.search, name='search'),
    url(r'^verify$', views.verify_email, name='verify'),
    url(r'^statistics/(?P<game_id>[0-9]+)/$', views.game_statistics, name='statistics'),
]

Online-Game-Store/GameShop/skeletor/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.sites.models import Site

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('django.contrib.auth.urls')),
    url(r'^', include('gameshop.urls', namespace='shop')),
]

Online-Game-Store/GameShop/gameshop/models.py
# coding=utf-8
from django.db import models
from django.contrib.auth.models import User
import gameshop.genre as game_genres #HUOM! 

class Score(models.Model):
    """ Model to keep all the scores in database """
    points = models.PositiveIntegerField()
    game = models.ForeignKey("Game", related_name="GameScores")
    user = models.ForeignKey(User, related_name="UserScores")

    class Meta:
        ordering = ["-points"]

    def __str__(self):
        return "{0}-{1}-{2}".format(self.game.name, self.user.username, self.points)

class Game(models.Model):
    """ Model to keep all the game infromation in database """
    name = models.CharField(max_length=225, unique=True)
    description = models.CharField(max_length=300)
    release_date = models.DateField(auto_now_add=True)
    game_developer = models.ForeignKey(User, related_name="DeveloperGames")
    publisher = models.CharField(max_length=225, blank=True)
    # GENRE_CHOICES omassa tiedostossa
    genre = models.CharField(max_length=225, choices=game_genres.GENRE_CHOICES)
    source = models.URLField(max_length=225, unique=True)
    price = models.FloatField()
    

    def sold_games(self):
        sum_of_prices=0
        soldgames=GameSale.objects.filter(game=self)
        for game in soldgames:
            sum_of_prices += game.gamePrice
        return sum_of_prices
    overall_sales = property(sold_games)
    
    def units(self):
        soldgames=GameSale.objects.filter(game=self)
        return len(soldgames)
    units_sold=property(units)

    def get_gamescores(self):
        return self.GameScores.all()
    leaderboard = property(get_gamescores)

    class Meta:
        ordering =["name"]

    def __str__(self):
        return self.name

class Gamer(models.Model):
    """ Extend User model with user.developer field """
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    library = models.ManyToManyField("Game")
    def addGame(self,game):
        self.library.add(game)
        sale=GameSale(game=game, gamePrice=game.price)
        sale.save()
        self.save()
    
    def __str__(self):
        return self.user.username


class Developer(models.Model):
    """ Extends User model with user.developer field """
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    def get_games(self):
        return self.user.DeveloperGames.all()
    inventory = property(get_games)
    def game_statistics(self):
        statistics={}
        for game in self.inventory:
            gamesales=GameSale.objects.filter(game=game)
            statistics[game.name]=gamesales
        return statistics
    statistics=property(game_statistics)

    def __str__(self):
        return self.user.username
	
class GameSave(models.Model):
    gameState=models.CharField(max_length=2250)
    game=models.ForeignKey('Game')
    user=models.ForeignKey(User)
    saveTime=models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering=["-saveTime"]
    
    def __str__(self):
        return "{0}-{1}-{2}".format(self.game.name, self.user.username, self.saveTime)

class GameSale(models.Model):
    game=models.ForeignKey('Game')
    timeBought=models.DateTimeField(auto_now_add=True)
    gamePrice=models.FloatField()
    
    class Meta:
        ordering=["-timeBought"]

    def __str__(self):
        return "{0}-{1}".format(self.game.name, self.timeBought)

Online-Game-Store/GameShop/gameshop/forms.py
# coding=utf-8
from django import forms
from django.contrib.auth.models import User 
from django.contrib.auth.forms import UserCreationForm      
from .models import Gamer, Developer, Game
from django.core import mail
from hashlib import md5

class RegistrationForm(UserCreationForm):
    username = forms.CharField(required = True, widget=forms.TextInput(attrs={'placeholder': 'Username'}))
    email = forms.EmailField(required = True, widget=forms.TextInput(attrs={'placeholder': 'Email'}))
    first_name = forms.CharField(required = False, widget=forms.TextInput(attrs={'placeholder': 'First Name'}))
    last_name = forms.CharField(required = False, widget=forms.TextInput(attrs={'placeholder': 'Last Name'}))
    developer = forms.BooleanField(label="Register as developer", required = False)
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Password'}),required = True)
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Confirm Password'}),required = True)

    class Meta:
        model = User
        fields = ['first_name','last_name','email','username', 'password1', 'password2',]

    def save(self,commit = True):   
        user = super(RegistrationForm, self).save(commit = False)
        user.email = self.cleaned_data['email']
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']

        if commit:
            print('saving user')
            user.is_active = False
            user.save()
            if self.cleaned_data['developer']:
                developer = Developer(user=user)
                developer.save()
            gamer = Gamer(user=user)
            gamer.save()

            secret_key = '6cd118b1432bf22942d93d784cd17084'
            checksumstr = "username={}&email={}&token={}".format(user.username, user.email, secret_key)
            m = md5(checksumstr.encode('ascii'))
            checksum = m.hexdigest()
            link = "http://localhost:8000/verify?&username={}&email={}&&checksum={}".format(user.username, user.email, checksum)
            with mail.get_connection() as connection:
                    mail.EmailMessage("Verify", link, "", [user.email],
                                                  connection=connection).send()


        return user

class PaymentForm(forms.Form):
    pid = forms.CharField(widget = forms.HiddenInput())
    sid = forms.CharField(widget = forms.HiddenInput())
    success_url = forms.URLField(widget = forms.HiddenInput())
    cancel_url = forms.URLField(widget = forms.HiddenInput())
    error_url = forms.URLField(widget = forms.HiddenInput())
    checksum = forms.CharField(widget = forms.HiddenInput())
    amount = forms.FloatField(widget = forms.HiddenInput())
    
class GameForm(forms.ModelForm):
    class Meta:
        model = Game
        fields = ['name', 'description', 'publisher', 'genre', 'source', 'price']

Online-Game-Store/GameShop/gameshop/views.py
# coding=utf-8

from django.shortcuts import render, get_object_or_404, get_list_or_404, render_to_response
from django.http import HttpResponseRedirect, HttpResponse   
from django.contrib import auth                 
from django.core.context_processors import csrf 
from django.contrib.auth.decorators import login_required
from .models import Score, Game, Gamer, Developer, GameSave
from .forms import RegistrationForm, PaymentForm, GameForm
from hashlib import md5
from django.contrib.auth.models import User
import json
import gameshop.genre as game_genres  
from django.template import RequestContext
from django.core.urlresolvers import reverse
from django.core import mail



def index(request):
    if not request.user.is_authenticated():
        template = 'registration/login.html'
    else:
        template = 'gameshop/index.html'
    context = {'user':request.user}
    return render(request, template, context)

def register(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        print("register")
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/')
    context = {}
    context.update(csrf(request))
    context['form'] = RegistrationForm()
    return render(request, 'gameshop/register.html', context)

@login_required(login_url='/')
def profile(request):
    context = {'user':request.user}
    return render(request, 'gameshop/profile.html', context)

def shop(request):
    if request.method == 'POST' and request.user.is_authenticated():
        game=get_object_or_404(Game,id=request.POST.get('game_id'))
        secret_key = '6cd118b1432bf22942d93d784cd17084' #
        pid = game.name
        sid = 'tester' #
        amount = str(game.price)
        checksumstr = "pid={}&sid={}&amount={}&token={}".format(pid, sid, amount, secret_key)
        m = md5(checksumstr.encode("ascii"))
        checksum = m.hexdigest()
        uri = request.build_absolute_uri()
        uri = uri.replace('shop','payment')
        print(uri)
        data = {
                'amount' : amount,
                'checksum' : checksum,
                'pid' : pid,
                'sid' : sid, 
                'success_url' : uri,
                'cancel_url' : uri,
                'error_url' : uri,
                }
        form = PaymentForm(None, initial=data)
        context = {'form':form}
        template = 'gameshop/payment.html'
    else:
        games = Game.objects.all()
        context = {'games':games, 'user':request.user}
        template = 'gameshop/shop.html'
    return render(request, template, context)

@login_required(login_url='/')
def play(request,game_id):
    game=get_object_or_404(Game,id=game_id)
    user = request.user
    if game in user.gamer.library.all():
        if request.is_ajax():
            if request.GET.get('messageType')=='SCORE':
                points = request.GET.get('score')
                scr = Score(points=points, game=game, user=user)
                scr.save()
                response_data = {'message': 'SUCCESS'}
                json_data = json.dumps(response_data)
                return HttpResponse(json_data, content_type="application/json")

            elif request.GET.get('messageType')=='SAVE':
                gameState = request.GET.get('gameState')
                saving=GameSave(gameState=gameState, game=game, user=user)
                saving.save()
                response_data = {'message': 'SUCCESS'}
                json_data = json.dumps(response_data)
                return HttpResponse(json_data, content_type="application/json")

            elif request.GET.get('messageType')=='LOAD_REQUEST':
                saving = get_list_or_404(GameSave, game=game, user=user)[0]
                gameState = saving.gameState
                response_data = {'messageType': 'LOAD', 'gameState': json.loads(gameState)}
                json_data = json.dumps(response_data)
                return HttpResponse(json_data, content_type="application/json")
            else: 
                scores = Score.objects.filter(game=game)[:10]
                context = {'game':game, 'scores':scores}
                return render(request, 'gameshop/game_scores.html', context)
        else:
            scores = Score.objects.filter(game=game)[:10]
            context = {'game':game, 'scores':scores}
            return render(request, 'gameshop/play.html', context)
    else:
        return HttpResponseRedirect('/')

@login_required(login_url='/')
def payment(request):
    context = {}
    if request.method == 'GET':
        context.update(csrf(request))
        res=request.GET.get('result')
        if res=='success':
            game_name = request.GET.get('pid')
            ref = request.GET.get('ref')
            secret_key = '6cd118b1432bf22942d93d784cd17084'
            checksumstr = "pid={}&ref={}&result={}&token={}".format(game_name, ref, res, secret_key)
            m = md5(checksumstr.encode('ascii'))
            checksum = m.hexdigest()
            if checksum == request.GET.get('checksum'):
                game = get_object_or_404(Game, name=game_name)
                template = 'gameshop/shop_success.html'
                context["game"]=game
                user=request.user
                user.gamer.addGame(game)
            else:
                template = 'gameshop/shop_error.html'
        elif res=='cancel':
            template = 'gameshop/shop_cancel.html'
        elif res=='error':
            template = 'gameshop/shop_error.html'
        context['res'] = res
    return render(request, template, context)

def developer(request):
    user = request.user
    context = {'user' : user}
    if user.is_authenticated and hasattr(user, 'developer'):
        inventory = user.developer.inventory.all()
        context['inventory'] = inventory
        statistics=user.developer.statistics
        context['statistics'] = statistics
        template = 'gameshop/developer.html'

        return render(request, template, context)
    else:
        return HttpResponseRedirect('/')

def game_statistics(request,game_id):
    user=request.user
    game=get_object_or_404(Game, id=game_id)
    if user.is_authenticated and hasattr(user, 'developer'):
        stats=user.developer.statistics[game.name]
        if game in user.developer.inventory.all():
            context = {'game': game, 'statistics': stats}    
            return render(request, 'gameshop/game_statistics.html', context)
    else:
        return HttpResponseRedirect('/')

def add_game(request):
    user = request.user
    if hasattr(user, 'developer'):
        if request.method == 'POST':
            form = GameForm(request.POST)
            if form.is_valid():
                game = form.save(commit=False)
                game.game_developer = request.user
                game.save()
                user.gamer.library.add(game)
                user.save()
                return HttpResponseRedirect('/developer')

        form = GameForm()
        context = {'form' : form}
        return render(request, 'gameshop/add_game.html', context)
    else:
        return HttpResponseRedirect('/')

@login_required(login_url='/')
def modify_game(request, game_id):
    user = request.user
    game = get_object_or_404(Game, id=game_id)
    if hasattr(user, 'developer'):
        if game in user.developer.inventory.all():
            form = GameForm(request.POST or None, instance = game)
            if form.is_valid():
                form.save()
                return HttpResponseRedirect('/developer')
            else:
                context = {'form' : form, 'game_id' : game_id}
                template = 'gameshop/add_game.html'
                return render(request, template, context)
    return HttpResponseRedirect('/')

@login_required(login_url='/')
def remove_game(request, game_id):
    user=request.user
    game=get_object_or_404(Game, id=game_id)
    if hasattr(user, 'developer'):
        if game in user.developer.inventory.all():
            game.delete()
    return HttpResponseRedirect('/developer')

def search(request):
    item=request.POST.get("search")
    games=list(Game.objects.filter(name=item))
    dictionary=dict(game_genres.GENRE_CHOICES)
    genres=list(dictionary.values())
    if item in genres:
        genre=list(dictionary.keys())[genres.index(item)]
        games.extend(list(Game.objects.filter(genre=genre)))
    context={'games': games}
    return render(request, 'gameshop/search.html', context)   

def verify_email(request):
    context = {}
    if request.method == 'GET':
        username = request.GET.get('username')
        email = request.GET.get('email')
        secret_key = '6cd118b1432bf22942d93d784cd17084' #
        checksumstr = "username={}&email={}&token={}".format(username, email, secret_key)
        m = md5(checksumstr.encode('ascii'))
        checksum = m.hexdigest()
        if checksum == request.GET.get('checksum'):
            user = get_object_or_404(User, username=username)
            user.is_active = True
            user.save()
            return HttpResponseRedirect('/')

    elif request.method == 'POST':
        username = request.POST.get('username')
        user = get_object_or_404(User, username=username)
        secret_key = '6cd118b1432bf22942d93d784cd17084'
        checksumstr = "username={}&email={}&token={}".format(username, user.email, secret_key)
        m = md5(checksumstr.encode('ascii'))
        checksum = m.hexdigest()
        link = "http://localhost:8000/verify?&username={}&email={}&&checksum={}".format(username, user.email, checksum)
        with mail.get_connection() as connection:
            mail.EmailMessage("Verify", link, "skeletor@skeletor.fi", [user.email],connection=connection).send()
        context['link_sended'] = True
        template = "gameshop/verify.html"
        return render(request, template, context)


    template = "gameshop/verify.html"
    return render(request, template, context)

Online-Game-Store/GameShop/gameshop/templates/gameshop/add_game.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}
Game settings
{% endblock %}


{% block content %}
<div class="container-fluid bg-1 text-center">
	<form class="form-horizontal" action="" method="POST">
		{% csrf_token %}
                {% for field in form %}
                <div class="form-group">
                    {{ field.label_tag }}
                    <span class="controls">
                        {{ field }}
                    </span>
                </div>
                {% endfor %}
                <div class="form-group" style="padding:10px;">
                    <div class="controls">
                        <button type="submit" class="btn">Save</button>
                    </div>
                </div>
	</form>
</div>
{% endblock %}

Online-Game-Store/GameShop/gameshop/templates/gameshop/developer.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}
Developer
{% endblock %}



{% block content %}
<div class="container-fluid bg-1 text-center">
    <div class="table-responsive col-md-8 col-md-offset-2">
        <h1 class="text-left">GAMES</h1>
        <p class="text-left">
            <a href="{% url 'shop:add' %}"><span class="btn btn-default glyphicon glyphicon-upload"></span></a>
            Upload a new game.
        </p>

        {% if inventory %}

        <table class="table-bordered" style="width:100%;">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Description</th>
                    <th>Game statistics</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                {% for game in inventory %}
                <tr>
                    <td>{{game.name}}</td>
                    <td>{{game.description}}</td>
                    <td><a href="{% url 'shop:statistics' game.id %}">See full stats</a>Total sales: {{game.overall_sales}}€ - Units sold: {{game.units_sold}}</td>

                        <td>
                            <a href="{% url 'shop:modify' game.id %}"><span class="btn btn-default glyphicon glyphicon-cog"></span></a>
                            <a href="{% url 'shop:remove' game.id %}"><span class="btn btn-default glyphicon glyphicon-trash"></span></a>
                        </td>

                        {% endfor %}
                        {% else %}
                        You have not added any games yet. 
                        {% endif %}


                    </tr>
                </tbody>
            </table>
        </div>   
    </div>
    {% endblock %}

Online-Game-Store/GameShop/gameshop/templates/gameshop/game_scores.html
<table id='Scores'>
    <caption>
	Leaderboard
    </caption>
{% if scores %}
    <tbody>
    {% for score in scores %}
        <tr>
            <td>{{forloop.counter}}.</td>
            <td>{{score.user.username}}</td>
            <td>{{score.points}}</td>
        </tr>
    {% endfor %}
    </tbody>	
{% endif %}
</table>

Online-Game-Store/GameShop/gameshop/templates/gameshop/game_statistics.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}
Statistics of {{ game.name }}
{% endblock %}

{% block navigation %}
{% include "navigation.html" %}
{% endblock %}

{% block content %}
<div class="container-fluid bg-1 text-center">
    <h1>Selling log of {{ game.name }}</h1>
    <div class="col-md-4 col-md-offset-4">
        <div class="table-responsive">
            <table class="table">
                <thead>
                    <tr>
                        <th>Price</th>
                        <th>Time</th>
                    </tr>
                </thead>
                <tbody>
                {% for stat in statistics %}
                    <tr>
                        <td>{{ stat.gamePrice }}€</td>
                        <td>{{ stat.timeBought }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}

Online-Game-Store/GameShop/gameshop/templates/gameshop/index.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}
    GameShop
{% endblock %}

{% block content %}
    <!-- First Container -->
    <div class="container-fluid bg-1 text-center">
    </div>
{% endblock %}

Online-Game-Store/GameShop/gameshop/templates/gameshop/payment.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}
Payment service
{% endblock %}



{% block content %}
<script>
    $(document).ready(function(){
    $("form").submit();
    });
</script>
<div class="container-fluid bg-1 text-center">
    Redirecting to Payment Service.
    <form action="" method="POST">
        {{ form }}
        <input type='submit' value='Buy' style="display:none"/>
    </form>
</div>
{% endblock %}

Online-Game-Store/GameShop/gameshop/templates/gameshop/play.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}
{{ game.name }}
{% endblock %}

{% block navigation %}
{% include "navigation.html" %}
{% endblock %}

{% block content %}
<script type="text/javascript">
/* global $ */
$(document).ready(function() {
    'use strict';
    $(window).on('message', function(evt) {
        //Note that only messages from game.source are accepted
        var origin = evt.origin || evt.originalEvent.origin;
        var game_origin = '{{ game.source }}'.split('/');
        game_origin.pop();
        if (origin !== game_origin.join('/'))
            return;

        //Get data from sent message
        var data = evt.originalEvent.data;
        var messageType=data.messageType;
          
        if (messageType === 'SAVE'){
            var tmp = { messageType: messageType,
                gameState : JSON.stringify(data.gameState)};
            data = tmp;
            }

        $.ajax({
            url:'',
            data: data,
            type: 'get',
            success: function(result) {
                if (result.messageType === 'LOAD'){
                    evt.originalEvent.source.postMessage(result, "*")
                    }
                }
            });

        if (messageType==='SCORE') {
            $('#tableContainer').load("{% url 'shop:play' game.id %}");
        }
        
        else if (messageType==='SETTING') {
            // set iframe size
            $('#game_iframe').css('width', data.options['width'])
            $('#game_iframe').css('height', data.options['height'])
        }
    });
});
</script>

<div class="container-fluid bg-1 text-center" style="heigth:100%;">
    <div class="row">
        <div class="col-md-8">
            <div class="text-center">
                <h1>{{ game.name }}</h1>
                <p>{{ game.description }}</p>
            </div>
            <iframe class="bg-3" id="game_iframe" src="{{game.source}}"></iframe>
        </div>
        <div class="col-md-4" id="tableContainer">
            {% include "gameshop/game_scores.html" %}
        </div>
    </div>
</div>
{% endblock %}

Online-Game-Store/GameShop/gameshop/templates/gameshop/profile.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}
Profile
{% endblock %}



{% block content %}
<div class="container-fluid bg-1 text-center">
    <table>
        <tr>
            <td>First name</td>
            <td>{{ user.first_name }}</td>
        </tr>
        <tr>
            <td>Last name</td>
            <td>{{ user.last_name }}</td>
        </tr>
        <tr>
            <td>Email</td>
            <td>{{ user.email }}</td>
        </tr>
    </table>
</div>
{% endblock %}

Online-Game-Store/GameShop/gameshop/templates/gameshop/register.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}
Register
{% endblock %}


{% block content %}
    <!-- First Container -->
    <div class="container-fluid bg-1 text-center">
        <div> 
            <form class="form-horizontal" action="" method="post"> 
            {% csrf_token %}
            {% for field in form %}
            <div class="form-group">
                {{ field.label_tag }}
                <span class="controls">
                    {{ field }}
                </span>
            </div>
            {% endfor %}
            <div class="form-group" style="padding:10px;">
                <div class="controls">
                    <button type="submit" class="btn">Register</button>
                </div>
            </div>
            </form>
    </div>
    </div>
{% endblock %}

Online-Game-Store/GameShop/gameshop/templates/gameshop/search.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}
Search
{% endblock %}


{% block content %}
<div class="container-fluid bg-1 text-center">
	{% if games %}
		{% for game in games %}
        {{ game.name }} - {{ game.description }} <br>
        {% endfor %}
	{% else %}
		Game not found. 
	{% endif %}
</div>
{% endblock %}

Online-Game-Store/GameShop/gameshop/templates/gameshop/shop.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}
GameShop
{% endblock %}


{% block content %}
<div class="container-fluid bg-1 text-center">
    {% if games %}
    <div class="table-responsive col-md-8 col-md-offset-2">
        <h1 class="text-left">GAMES</h1>
        <table class="table-bordered" style="width:100%;">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Genre</th>
                    <th>Description</th>
                    <th>Publisher</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                {% for game in games %}
                <tr>
                    <td> {{ game.name }} </td>
                    <td> {{ game.get_genre_display }} </td>
                    <td> {{ game.description }} </td>
                    <td> {{ game.publisher }} </td>
                    {% if game in user.gamer.library.all %}
                    <td>
                        <a href="{% url 'shop:play' game.id %}"><span class="btn btn-default">Play</span></a>
                    </td>
                    {% elif user.is_authenticated %}
                    <td>
                        <form action="" method="POST">
                            {% csrf_token %}
                            <input id="id_game_id" name="game_id" type="hidden" value="{{ game.id }}" />
                            <button type="submit" class="btn btn-default">{{game.price}}<span class="glyphicon glyphicon-euro"></span>
                            </button>
                        </form>
                    </td>   
                    {% else %}
                    <td>
                        <a href="{% url 'shop:index' %}"><span class="btn btn-default glyphicon glyphicon-log-in"></span></a>
                    </td>
                    {% endif %}

                    {% endfor %}
                </tr>
            </tbody>
        </table>
    </div>
    {% else %}
    The store is empty at the moment.
    {% endif %}
</div>
{% endblock %}

Online-Game-Store/GameShop/gameshop/templates/gameshop/shop_cancel.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}
Payment
{% endblock %}

{% block navigation %}
{% include "navigation.html" %}
{% endblock %}

{% block content %}
<div class="container-fluid bg-1 text-center">
	Your transaction was canceled!
</div>
{% endblock %}

Online-Game-Store/GameShop/gameshop/templates/gameshop/shop_success.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}
Payment
{% endblock %}

{% block navigation %}
{% include "navigation.html" %}
{% endblock %}

{% block content %}
<div class="container-fluid bg-1 text-center">
	Your transaction was successful!
	<br>
	<a href="{% url 'shop:play' game.id %}">Play</a>
	<br>
	<a href="{% url 'shop:shop' %}">Continue shopping</a>
</div>
{% endblock %}

Online-Game-Store/GameShop/gameshop/templates/gameshop/verify.html
{% extends "base.html" %}
{% block title %}
Verify Email
{% endblock %}

{% block content %}
<div class="container-fluid bg-1 text-center">

{% if not link_sended %}
<div id="verify"> 
    <p>Give your username and verification link will be sent to your email.</p>
        <form class="form-horizontal" action="" method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="username">Username</label>
            <div class="controls">
                <input type="text" id="username" name="username"  placeholder="Username">
            </div>
        </div>
        <div class="form-group" style="padding:10px;">
            <div class="controls">
                <button type="submit" class="btn">Send link</button>
            </div>
        </div>
        </form>
    </div>
{% else %}
<p>Link has been sended to your email.</p>
{% endif %}
</div>
{% endblock %}